version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pm2-go
    main: ./cmd/pm2-go
    binary: pm2-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
  - id: pm2-go-web
    main: ./cmd/pm2-go-web
    binary: pm2-go-web
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - id: pm2-go
    ids:
      - pm2-go
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  - id: pm2-go-web
    ids:
      - pm2-go-web
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
